In [1]:
import numpy as np

# 1. Sukurkite tokį ndarray ir išsaugokite kintamąjame arr:

In [4]:
arr = np.array( [
    [5,4,3],
    [3,2,1],
    [1,0,6],
    [6,5,4],
    ]
)

arr

array([[5, 4, 3],
       [3, 2, 1],
       [1, 0, 6],
       [6, 5, 4]])

# 2. Kiek dimensijų turi arr? Kokios jos?

In [6]:
arr.shape

(4, 3)

# 3. Atspausdinkite 3-ios eilutės antrąjį narį

In [9]:
print(arr [2, 1])

0


# 4. Atspausdinkite 2-os eilutės pirmą ir antrą narius

In [11]:
print(arr [1, 0:2])

[3 2]


# 5. Atspausdinkite 3-ios ir 4 eilučių antrą ir trečią narius (t.y. iš viso 4 skaičius iš dešiniojo apatinio kampo)

In [12]:
print(arr [2:5, 1:3])

[[0 6]
 [5 4]]


# 6. Naudodami reshape() metodą pakeiskite arr taip, kad jo dimensijos būtų (6, 2)

In [13]:
arr.reshape(6,2)

array([[5, 4],
       [3, 3],
       [2, 1],
       [1, 0],
       [6, 6],
       [5, 4]])

# 7. Transponuokite arr (po transponavimo shape turi būti (2, 6))

In [25]:
arr.reshape(6,2).transpose()


array([[5, 3, 2, 1, 6, 5],
       [4, 3, 1, 0, 6, 4]])

# 8. Padauginkite visus šio array skaičius iš 8 ir atimkite iš visų 30, išsaugokite rezultatą kintamąjame arr_2

In [26]:
arr = arr.reshape(6,2).transpose()

In [32]:
arr_2 = arr * 8 - 30
print(arr_2)

[[ 10  -6 -14 -22  18  10]
 [  2  -6 -22 -30  18   2]]


# 9. Priskirkite visus neigiamus arr_2 narius kintamąjam arr_2_neg

In [38]:
arr_2_neg = arr_2[arr_2 < 0]
print(arr_2_neg)

[ -6 -14 -22  -6 -22 -30]


# 10. Atspausdinkite arr_2_neg narių sumą ir sandaugą

In [42]:
print(arr_2_neg.sum())
print(arr_2_neg.prod())

-100
7318080


# 11. Atspausdinkite arr_2_neg medianą

In [49]:
print(np.median(arr_2_neg))

-18.0
