In [2]:
def anomaly_2(my_list):
    for left_number, right_number in zip(my_list[:-1], my_list[1:]):
        print(left_number, right_number)

In [3]:
my_list = [17,18,19,21]
print (my_list[:-1])
print(my_list[1:])

anomaly_2(my_list)

[17, 18, 19]
[18, 19, 21]
17 18
18 19
19 21


In [ ]:
for number in range(1,101):
    result_text = ''
    if number % 2 == 0:
        result_text += 'Fizz'
    if number % 3 == 0:
        result_text +='Buzz'
    print(result_text)
    
    

# Numpy

In [6]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Greta\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [7]:
import numpy as np

In [14]:
a_list = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

print(a_list[1][1])
print([row[1] for row in a_list])

6
[2, 6, 10]


In [18]:
a_np = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
    ]
)

print(a_np)
print(type(a_np))
print(a_np [1][1])
print(a_np [1, 1]) # row index, column index
print(a_np [:, 1])
print(a_np [:2, 1])
print(a_np [:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
6
6
[ 2  6 10]
[2 6]
[[2 3]
 [6 7]]


In [19]:
a_np.shape # 3 eilutes ir 4 stulpeliai 

(3, 4)

## 1D array

In [20]:

array_1d = np.array( [1,5,7,9,71,14])

In [23]:
print(array_1d.shape)
print(len(array_1d))

(6,)
6


In [24]:
print(array_1d)

[ 1  5  7  9 71 14]


## 3D array

In [25]:
arr = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
]
)

In [26]:
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [27]:
print(arr.shape)

(2, 2, 3)


In [29]:
np.random.randn(2,5)

array([[-1.08153386,  1.66215127, -0.03823886,  0.50325852, -0.29625908],
       [-0.43573137,  0.64578742, -1.36810819,  0.93471298,  0.18256039]])

## Numpy operations

In [31]:
py_list = [1,2,3,4,5]
print(py_list * 3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [34]:
np_array = np.array ([1,2,3,4,5])
print(np_array * 3)
print(np_array / 3)
print(np_array ** 3)

[ 3  6  9 12 15]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[  1   8  27  64 125]


In [35]:
py_list[2:4] = 100

TypeError: can only assign an iterable

In [39]:
np_array [2:4] = 100
print(np_array)
np_array [2:4] = [100, 200]
print(np_array)

[  1   2 100 100   5]
[  1   2 100 200   5]


## numpy speed

In [44]:
size = 100000
py_list = list(range(size))
np_arr = np.arange(size)

In [41]:
%%timeit

list_rez = []
for number in py_list:
    list_rez.append(number * 10)

9.52 ms ± 835 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
%%timeit

np_rez = np_arr * 10

98.6 µs ± 8.67 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


# Reshape

In [46]:
np_array = np.arange(0,100,2)
print(np_array)
print(np_array.shape)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)


In [47]:
print(np_array.reshape((5,10)))

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [51]:
print(np_array.reshape((2,1,-1)))

[[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44
   46 48]]

 [[50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
   96 98]]]


# numpy methods

In [62]:
print(array_1d)
print(np.mean(array_1d, axis= 0))

[ 1  5  7  9 71 14]
17.833333333333332


In [64]:
np.std(arr, axis=0)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [67]:
np.sum(arr, axis=1)

array([[5, 7, 9],
       [5, 7, 9]])

In [68]:
arr.transpose()

array([[[1, 1],
        [4, 4]],

       [[2, 2],
        [5, 5]],

       [[3, 3],
        [6, 6]]])

In [70]:
np_array = np.arange(0,60,2)
print(np_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58]


In [71]:
np_array [np_array < 30]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [72]:
np_array < 30

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])